name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout GitHub repository
      uses: actions/checkout@v2

    - name: Setup Node environment
      uses: actions/setup-node@v3
      with:
        node-version: '16.14.2'

    - name: Install project modules
      run: npm ci

    - name: Run ESLint
      run: npm run lint